cask_args appdir: '/Applications'

brew 'curl'
brew 'git'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'openssl'
brew 'telnet'

# フロントエンド系
brew 'nodebrew'

cask 'cyberduck'
cask 'docker'
cask 'github'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'google-cloud-sdk'
cask 'karabiner-elements'
cask 'ngrok'
cask 'visual-studio-code'
cask 'slack'
cask 'box-sync'
cask 'postman'
cask 'evernote'
cask 'parallels'
cask 'zoomus'
cask 'hyperswitch'
cask 'iterm2'
cask 'coteditor'
cask 'discord'
